[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
arti-client = "0.44.0"
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["tokio-macros", "net", "rt"] }
uniffi = { version = "0.32.0", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.32.0", features = ["build"] }

[[bin]]
name = "uniffi-bindgen"
path = "src/uniffi-bindgen.rs"
